[".config/alacritty/catppuccin"]
type = "git-repo"
url = "https://github.com/catppuccin/alacritty.git"
refreshPeriod = "168h"

[".config/zsh/lib/key-bindings.zsh"]
type = "file"
url = "https://github.com/ohmyzsh/ohmyzsh/raw/master/lib/key-bindings.zsh"
refreshPeriod = "168h"

[".local/share/miniplug/miniplug.zsh"]
type = "file"
url = "https://git.sr.ht/~yerinalexey/miniplug/blob/master/miniplug.zsh"
refreshPeriod = "168h"
