[".config/alacritty/catppuccin"]
type = "git-repo"
url = "https://github.com/catppuccin/alacritty.git"
refreshPeriod = "168h"

[".config/nvim"]
type = "archive"
url = "https://github.com/AstroNvim/AstroNvim/archive/master.tar.gz"
stripComponents = 1
refreshPeriod = "168h"

[".local/share/miniplug/miniplug.zsh"]
type = "file"
url = "https://git.sr.ht/~yerinalexey/miniplug/blob/master/miniplug.zsh"
refreshPeriod = "168h"
