#!/usr/bin/env bash

idletime() {
  now=$(date +%s)
  starttime=$(eww get idle_start)

  date -ud "0 $now sec - $starttime sec" +"%-H hours, %-M minutes" |
    awk -F ', ' '{ if ($1 == "0 hours") { sub("0 hours, ","") } else { sub(", 0 minutes","") }; print }' |
    awk '{ sub("1 hours","1 hour"); sub("1 minutes","1 minute"); print }'
}

lock() {
  open
  # swaylock may fail if already running
  (swaylock && close) &
}

close() {
  # don't close if swaylock is running
  if pidof -q swaylock; then
    return
  fi

  eww open bar >/dev/null
  eww close idle >/dev/null 2>/dev/null || true
}

open() {
  eww update idle_start=$(date +%s)
  eww open idle >/dev/null
  eww close bar >/dev/null 2>/dev/null || true
}

if [ "$1" = "time" ]; then
  idletime
elif [ "$1" = "lock" ]; then
  lock
elif [ "$1" = "close" ]; then
  close
else
  open
fi
