#!/usr/bin/env bash

idletime() {
  now=$(date +%s)
  starttime=$(eww get idle_start)

  date -ud "0 $now sec - $starttime sec" +"%-H hours, %-M minutes" |
    awk -F ', ' '{ if ($1 == "0 hours") { sub("0 hours, ","") } else { sub(", 0 minutes","") }; print }' |
    awk '{ sub("1 hours","1 hour"); sub("1 minutes","1 minute"); print }'
}

lock() {
  open
  eww update locked=true
  # swaylock may fail if already running
  (swaylock && close) &
}

suspend() {
  caffeine=$(eww get caffeine)
  if [ "$caffeine" = "false" ]; then
    systemctl suspend
  fi
}

close() {
  # don't close if swaylock is running
  if pidof -q swaylock; then
    return
  fi

  eww open bar >/dev/null
  eww close idle >/dev/null 2>/dev/null || true
}

open() {
  if pidof -q swaylock; then
    return
  fi
  # add how many seconds to time counter
  sec=${1-0}

  eww update idle_start=$(($(date +%s) - (sec)))
  eww open idle >/dev/null
  eww close bar >/dev/null 2>/dev/null || true
}

if [ "$1" = "time" ]; then
  idletime
elif [ "$1" = "lock" ]; then
  lock
elif [ "$1" = "suspend" ]; then
  suspend
elif [ "$1" = "close" ]; then
  close
else
  open "$1"
fi
