#!/bin/env bash

get() {
    connection=$(nmcli -t connection show --active)

    ethernet=$(grep 'ethernet' <<< "$connection" | cut -f 1 -d ':')
    if [ -n "$ethernet" ]; then
        # connected to ethernet
        jq -ncM "{ device: \"ETHERNET\", label: \"$ethernet\" }"
        return
    fi

    wifi=$(grep 'wireless' <<< "$connection" | cut -f 1 -d ':')
    if [ -n "$wifi" ]; then
        # connected to wifi
        signal=$(nmcli -t -fields ACTIVE,SIGNAL device wifi | awk -F ':' '{ if ($1 == "yes") print $2 }')
        jq -ncM "{ device: \"WIFI\", label: \"$wifi\", signal: $signal }"
        return
    fi

    wifienable=$(nmcli -t general | cut -f 4 -d ':')
    if [ "$wifienable" = "enabled" ]; then
        # wifi enabled, not connected
        jq -ncM "{ device: \"WIFI\", label: \"Wifi\", signal: 0 }"
        return
    fi

    jq -ncM "{ device: \"NONE\", label: \"No Connection\" }"
}

# initial value
get

# https://github.com/waltinator/net-o-matic/blob/master/net-o-matic#L152
ip monitor link | \
    grep -E --line-buffered '[[:digit:]]+: [[:alnum:]]+: <.*>' | \
    while read line ; do
    get
done
