#!/bin/env bash

get() {
  workspaces=$(hyprctl workspaces -j)
  clients=$(hyprctl clients -j)
  monitors=$(hyprctl monitors -j)
  apps=$(jq '' ./apps.json)

  jq -ncM -f 'scripts/workspace.jq' --argjson workspaces "$workspaces" --argjson clients "$clients" --argjson monitors "$monitors" --argjson apps "$apps"
}

# print initial value
get

catch=('activewindow' 'closewindow' 'windowtitle' 'workspace' 'focusedmon')

# connect to hyprland socket
nc -U /tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock | while read line; do
  event=$(echo $line | awk -F '>>' '{ print $1 }')

  if [[ "${catch[*]}" =~ "$event" ]]; then
    get
  fi
done
