#!/usr/bin/env bash

get() {
  vol=$(amixer -D pulse sget Master | grep 'Left:' | awk -F'[][]' '{ print $2 }' | tr -d '%')
  mute=$(amixer -D pulse sget Master | grep '\[on\]' -q && echo 'false' || echo 'true')
  mic=$(amixer -D pulse sget Capture | grep 'Left:' | awk -F'[][]' '{ print $2 }' | tr -d '%')
  mic_mute=$(amixer -D pulse sget Capture | grep '\[on\]' -q && echo 'false' || echo 'true')

  jq -ncM "{ volume: $vol, mute: $mute, mic: $mic, mic_mute: $mic_mute }"
}

get

stdbuf -oL amixer sevents |
  grep --line-buffered "value:" | while read -r line; do
  get

  if grep -q "Master" <<<"$line"; then
    "$HOME/.config/eww/scripts/popup-osd" volume
  elif grep -q "Capture" <<<"$line"; then
    "$HOME/.config/eww/scripts/popup-osd" mic
  fi
done
