#!/usr/bin/env bash

update_osds() {
  # This function updates $osds in the calling parent.
  # Probably because they happened to share the same name,
  # I don't know why it works. It works though.

  osds=$1
  query=$2

  osds=$(echo "$osds" | jq -Mc "$query")
  eww update osds="$osds"

  # echo $osds
}

open_osd() {
  eww open osd >/dev/null

  osds=$(eww get osds | sed 's/^$/[]/')
  type=${1-:volume}
  current=$(date +%s)

  osdObj="{ type: \"$type\", widget: \"(osd-$type)\", open_time: $current }"
  index_of="index( map(select(.type == \"$type\"))[0] )"

  # not overriding .reveal so already-open ones wouldn't replay animation
  update_osds "$osds" ".[$index_of // length] += $osdObj"

  update_osds "$osds" ".[$index_of].reveal = true"

  clean_osds

  sleep 5 && clean_osds &
}

close_osd() {
  type=$1
  index_of="index( map(select(.type = \"$type\"))[0] )"

  osds=$(eww get osds)
  update_osds "$osds" ".[$index_of].reveal = false"

  sleep 0.55

  osds=$(eww get osds)
  update_osds "$osds" ".[$index_of // empty] += { widget: \"\", reveal: true }"
  update_osds "$osds" "del(.[$index_of // empty])"

  if [ "$osds" = "[]" ]; then
    eww close osd >/dev/null 2>/dev/null || true
  fi
}

clean_osds() {
  osds=$(eww get osds)
  current=$(date +%s)

  # find outlived osds (over 5s) AND only preserve last two
  echo "$osds" | jq -Mcr --argjson current "$current" \
    'length as $len | to_entries | # .key => index; .value => osdObj
    map(select(.key < ($len - 2) or ($current - .value.open_time) >= 5 )) |
    map(.value.type)[]' |
    while read -r type; do
      # echo "closing $type"
      close_osd "$type" &
    done
}

open_osd "$1"
