#!/usr/bin/env bash

toggle_widget() {
  WIDGET=$1
  TOGGLE=$2 # "open" or "close" or empty

  # Run eww daemon if not running
  if ! eww ping &>/dev/null; then
    eww daemon
    sleep 1
  fi

  close() {
    [ "$TOGGLE" != "open" ] &&
      eww close "$WIDGET" &>/dev/null &&
      echo "Closed $WIDGET"
  }

  open() {
    [ "$TOGGLE" != "close" ] &&
      eww open "$WIDGET" &>/dev/null &&
      echo "Opened $WIDGET"
  }

  close || open
}

menu() {
  sh "$HOME/.config/rofi/scripts/$1"
}

if [[ "$1" =~ dashboard|calendar ]]; then
  toggle_widget "$1" "$2"
  exit
fi

# don't launch immediately so eww doesn't freeze
sleep 0.05

toggle_widget dashboard close || true

case "$1" in
  browser)
    firefox
    ;;
  incognito)
    firefox --private-window
    ;;
  bluetooth)
    blueman-manager
    ;;
  network)
    nm-connection-editor
    ;;
  launcher)
    menu launcher.sh
    ;;
  audio)
    menu audio.sh
    ;;
  game)
    menu game-lib.sh
    ;;
  screenshot)
    menu screenshot.sh
    ;;
  emoji)
    menu emoji.sh
    ;;
  calc)
    menu calc.sh
    ;;
  terminal)
    alacritty
    ;;
  extern-desktop)
    alacritty -e sh -c 'extern-desktop.sh'
    ;;
  update)
    alacritty --hold -e sh -c 'yay -Syu'
    ;;
esac
