#!/usr/bin/env bash

TODO='-'
FIN='\*'
SPACE=' *'

FILE=/data/sync/stuff/markdeez/就做點事plz.md

add_task() {
  echo "- [ ] $*" >>"$FILE"
}

dialog_add_task() {
  task=$(zenity --entry \
    --width 500 \
    --title "New Task" \
    --text "Create a new To-Do task with the following label:")
  if [ -n "$task" ]; then
    add_task "$task"
  fi
}

remove_task() {
  sed -i "${*}d" "$FILE"
}

remove_finished() {
  sed -i "/^\* .*/d" "$FILE"
}

do_task() {
  sed -i "${*}s/^\\( *\\)- \\[ \\] *\\(.*\\)/\\1- [x] \\2/" "$FILE"
}

undo_task() {
  sed -i "${*}s/^\\( *\\)- \\[x\\] *\\(.*\\)/\\1- [ ] \\2/" "$FILE"
}

list_tasks() {
  perl -nlwe '/( *)- \[([x ])\] (.*)/ && print join "\t", $., length($1) / 4, $2, $3' "$FILE" |
    jq -nRcM '[inputs | split("\t") | { index: .[0], indent: .[1], completed: (.[2] == "x"), content: (.[3:] | join("\t")) }]'
}

case $1 in
  add)
    add_task "${@:2}"
    ;;
  dialog_add | ask)
    dialog_add_task
    ;;
  remove)
    remove_task "${@:2}"
    ;;
  remove_finished)
    remove_finished
    ;;
  do)
    do_task "${@:2}"
    ;;
  undo)
    undo_task "${@:2}"
    ;;
  list)
    list_tasks
    ;;
  subscribe)
    tail -F "$FILE" | while read -r _line; do
      list_tasks
    done
    ;;
esac
