#!/usr/bin/env bash

get() {
  vol=$(amixer -D pulse sget Master | grep 'Left:' | awk -F'[][]' '{ print $2 }' | tr -d '%')
  mute=$(amixer -D pulse sget Master | grep '\[on\]' -q && echo 'false' || echo 'true')
  mic=$(amixer -D pulse sget Capture | grep 'Left:' | awk -F'[][]' '{ print $2 }' | tr -d '%')
  mic_mute=$(amixer -D pulse sget Capture | grep '\[on\]' -q && echo 'false' || echo 'true')

  jq -ncM "{ volume: $vol, mute: $mute, mic: $mic, mic_mute: $mic_mute }"
}

get

pactl subscribe |
  grep --line-buffered "sink" | while read -r line; do
  get

  "$HOME/.config/eww/scripts/osd_popup" volume
done
