#!/usr/bin/bash

updates=$(checkupdates)
aur=$(yay -Qu)

if [ -n "$aur" ]; then
  updates="$updates$aur"
fi

updates=$(echo "$updates" | sort | uniq)

if [ -n "$updates" ]; then
  count=$(echo "$updates" | wc -l)

  jq -ncM "{ count: $count, packages: \"$updates\" }"
else
  jq -ncM '{ count: 0, packages: "Packages up-to-date! :)" }'
fi
