#!/usr/bin/bash

updates=$(checkupdates)
aur=$(yay -Qu)

if [ -n "$updates" ] && [ -n "$aur" ]; then
  updates="$updates\n$aur"
elif [ -n "$aur" ]; then
  updates="$aur"
fi

updates=$(echo "$updates" | uniq | sort)

if [ -n "$updates" ]; then
  count=$(echo "$updates" | wc -l)

  jq -ncM "{ count: $count, packages: \"$updates\" }"
else
  jq -ncM '{ count: 0, packages: "Packages up-to-date! :)" }'
fi
