"$schema" = "https://starship.rs/config-schema.json"

# Inserts a blank line between shell prompts
add_newline = true

format = """$os$all\
$line_break\
$character
"""

right_format = "$hostname$cmd_duration$time"

[cmd_duration]
format = "[󱦟 $duration]($style) "

[directory]
read_only = " 󰌾"
read_only_style = "bold cyan"
repo_root_style = "bold underline cyan"
truncation_symbol = "…/"
fish_style_pwd_dir_length = 1

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
symbol = "󰘬 "

[git_commit]
format = '[\(󰜛$hash$tag\)]($style) '

[git_status]
stashed = "*"
deleted = ""
ahead = "↑"
behind = "↓"

[hostname]
format = "[$ssh_symbol$hostname]($style) "
ssh_symbol = " "

[os]
disabled = false

[package]
format = "[$symbol$version]($style) "
symbol = "󰏗 "

[status]
disabled = false
symbol = " "
not_executable_symbol = "󰜺 "
not_found_symbol = "󰍊 "
sigint_symbol = " "
signal_symbol = "󱐋"
pipestatus = true
pipestatus_format = "\\[$pipestatus\\] [$signal_name$maybe_int]($style)"

[time]
disabled = false
format = "[󱑒 $time]($style) "


[aws]
symbol = "  "

[buf]
symbol = " "

[bun]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

# [directory]
# read_only = " 󰌾"

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fossil_branch]
symbol = "󰘬 "

# [git_branch]
# symbol = "󰘬 "

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = "⌘ "

[hg_branch]
symbol = "󰘬 "

# [hostname]
# ssh_symbol = " "

[java]
symbol = " "

[jobs]
symbol = "✦ "

[julia]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = "󱓞 "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

# [package]
# symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[pixi]
symbol = "󰏗 "

[pulumi]
symbol = " "

[purescript]
symbol = " "

[python]
symbol = " "

[raku]
symbol = "󱖊 "

[red]
symbol = "󱍼 "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "

[scala]
symbol = " "

[shlvl]
symbol = "󰹍 "

[singularity]
symbol = " "

[solidity]
symbol = " "

[spack]
symbol = " "

[sudo]
symbol = " "

[swift]
symbol = " "

[terraform]
symbol = " "

[vlang]
symbol = " "

[typst]
symbol = " "

[vagrant]
symbol = " "

[xmake]
symbol = " "

[zig]
symbol = " "
