#!/usr/bin/env bash

# Start daemons
fcitx5 -d
dunst &
swayidle -w &
/usr/lib/kdeconnectd &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

swww init && sleep 1 && swww query && sh "$HOME"/.config/hypr/scripts/set-wallpapr
eww daemon && eww open bar &&
  eww open dashboard && eww close dahsboard &&
  keepassxc &
openrgb -p 'Breath.' --startminimized

# Start programs
webcord -m --enable-features=UseOzonePlatform --ozone-platform=wayland &
flatpak run chat.revolt.RevoltDesktop --enable-wayland-ime \
  --enable-features=UseOzonePlatform --ozone-platform=wayland &
firefox &
