#!/usr/bin/env bash

notify() {
    dunstify -h int:value:"$1" -h string:hlcolor:"$2" -h string:x-dunst-stack-tag:"$3" "$4"
}

volume() {
    current=$(amixer -D pulse sset Master 5%$1 \
        | grep 'Left:' | awk -F'[][]' '{ print $2 }' | tr -d '%')

    dunstify -h int:value:"$current" -h string:hlcolor:#b4bdf8 -h string:x-dunst-stack-tag:volume \
        "Current Volume $current%"
}

mute() {
    muted=$(amixer -D pulse sset Master toggle \
        | grep '\[on\]' -q && echo "Unmuted" || echo "Muted")

    dunstify -h string:x-dunst-stack-tag:volume "Audio $muted"
}

player() {
    case $1 in
        play)
            playerctl play-pause
            ;;
        stop)
            playerctl stop
            ;;
        next)
            playerctl next
            ;;
        prev)
            playerctl previous
            ;;
    esac
}

if [ "$1" = "vol" ]; then
    volume "$2"
elif [ "$1" = "mute" ]; then
    mute
elif [ "$1" = "player" ]; then
    player "$2"
fi
