#!/usr/bin/env bash

volume() {
  amixer -D pulse sset Master 5%$1 |
    grep 'Left:' | awk -F'[][]' '{ print $2 }' | tr -d '%'

  "$HOME/.config/eww/scripts/osd_popup" volume
}

mute() {
  amixer -D pulse sset Master toggle |
    grep '\[on\]' -q && echo "Unmuted" || echo "Muted"

  "$HOME/.config/eww/scripts/osd_popup" volume
}

player() {
  case $1 in
    play)
      playerctl play-pause
      ;;
    stop)
      playerctl stop
      ;;
    next)
      playerctl next
      ;;
    prev)
      playerctl previous
      ;;
  esac
}

if [ "$1" = "vol" ]; then
  volume "$2"
elif [ "$1" = "mute" ]; then
  mute
elif [ "$1" = "player" ]; then
  player "$2"
fi
